/**
 * Portions of the code were generated by the Github Copilot AI
 */

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.fxml.Initializable;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.*;
import javafx.scene.input.KeyEvent;
import javafx.stage.Stage;

import java.io.IOException;
import java.net.URL;
import java.util.ResourceBundle;

public class AdminController implements Initializable {

    @FXML
    private TextField wordLength;
    @FXML
    private TableView<CustomTableRow> fileTable;

    /**
     * @param url
     * @param resourceBundle
     */
    @Override
    public void initialize(URL url, ResourceBundle resourceBundle) {
        wordLength.addEventFilter(KeyEvent.KEY_TYPED, keyEvent -> {
            if (!"0123456789".contains(keyEvent.getCharacter())) {
                keyEvent.consume();
            }
        });
        wordLength.setOnAction(actionEvent -> setWordLength());
    }

    public void setWordLength() {
        String length = wordLength.getText();
        if (length.length() > 0) {
            WordBank.setWordLength(Integer.parseInt(length));
        }
    }

    public void addNewWordFile() {
        TableColumn<CustomTableRow, ?> actionColumn = fileTable.getColumns().get(1);
        actionColumn.setCellFactory(param -> new TableCell<CustomTableRow, Button>() {
            private void updateItem(Button item, boolean empty) {
                super.updateItem(item, empty);
                if (empty || item == null) {
                    setGraphic(null);
                } else {
                    setGraphic(item);
                }
            }
        });
    }

    public static void loadAdminDashboard(Stage stage) throws IOException {
        FXMLLoader loader = new FXMLLoader(AdminController.class.getResource("admin-dashboard.fxml"));
        Parent root = loader.load();
        Scene scene = new Scene(root);
        stage.setScene(scene);
    }
}
