/** A large portion of this code was generated by ChatGPT, using the prompt:
 * <p>
 *    Using JavaFX and Scenebuilder,  a table view is made with two columns: File and Action. Write code
 *    that allows me to edit the File column by inserting a file string and edit the Action column by
 *    inserting a button.
 * </p>
 *
**/
import javafx.scene.control.Button;

public class CustomTableRow {
    private final String file;
    private final Button actionButton;

    public CustomTableRow(String file) {
        this.file = file;
        this.actionButton = new Button("Set");
    }

    public String getFile() {
        return file;
    }

    public

    public Button getActionButton() {
        return actionButton;
    }
}
